// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/entities/habit_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8277559469672140008),
    name: 'HabitEntity',
    lastPropertyId: const obx_int.IdUid(14, 2340576318155093400),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8259134062068990707),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 602968145928933391),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8749130872974233300),
        name: 'measureType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4575227963511126212),
        name: 'measureAmount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5426996704367716109),
        name: 'measureDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8922404341493588185),
        name: 'measureTimeInMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5063879269821670159),
        name: 'measureRepetitionsCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7712698515501611139),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1235743817356870237),
        name: 'iconColor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7258864788484630674),
        name: 'iconBackground',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3628490823299390692),
        name: 'reminderTimestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6409431907359169471),
        name: 'reminderVibrate',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2340576318155093400),
        name: 'reminderSound',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6218435188947418762),
    lastIndexId: const obx_int.IdUid(1, 1312269993216131232),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [6218435188947418762],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1290215926709979481,
      938897737165323226,
      2422719365508688050,
      8975223381343888019,
      3732623046559763645,
      3215958582535090281,
      6273806563025371401,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    HabitEntity: obx_int.EntityDefinition<HabitEntity>(
      model: _entities[0],
      toOneRelations: (HabitEntity object) => [],
      toManyRelations: (HabitEntity object) => {},
      getId: (HabitEntity object) => object.id,
      setId: (HabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (HabitEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final measureTypeOffset = fbb.writeString(object.measureType);
        final measureDescriptionOffset = object.measureDescription == null
            ? null
            : fbb.writeString(object.measureDescription!);
        final iconOffset = fbb.writeString(object.icon);
        final iconColorOffset = fbb.writeString(object.iconColor);
        final iconBackgroundOffset = fbb.writeString(object.iconBackground);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, measureTypeOffset);
        fbb.addInt64(4, object.measureAmount);
        fbb.addOffset(5, measureDescriptionOffset);
        fbb.addInt64(6, object.measureTimeInMinutes);
        fbb.addInt64(7, object.measureRepetitionsCount);
        fbb.addOffset(8, iconOffset);
        fbb.addOffset(9, iconColorOffset);
        fbb.addOffset(10, iconBackgroundOffset);
        fbb.addInt64(11, object.reminderTimestamp);
        fbb.addBool(12, object.reminderVibrate);
        fbb.addBool(13, object.reminderSound);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final measureTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final measureAmountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final measureDescriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final measureTimeInMinutesParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final measureRepetitionsCountParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 18);
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final iconColorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final iconBackgroundParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final reminderTimestampParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final reminderVibrateParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final reminderSoundParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final object = HabitEntity(
          id: idParam,
          name: nameParam,
          measureType: measureTypeParam,
          measureAmount: measureAmountParam,
          measureDescription: measureDescriptionParam,
          measureTimeInMinutes: measureTimeInMinutesParam,
          measureRepetitionsCount: measureRepetitionsCountParam,
          icon: iconParam,
          iconColor: iconColorParam,
          iconBackground: iconBackgroundParam,
          reminderTimestamp: reminderTimestampParam,
          reminderVibrate: reminderVibrateParam,
          reminderSound: reminderSoundParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HabitEntity] entity fields to define ObjectBox queries.
class HabitEntity_ {
  /// See [HabitEntity.id].
  static final id = obx.QueryIntegerProperty<HabitEntity>(
    _entities[0].properties[0],
  );

  /// See [HabitEntity.name].
  static final name = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[1],
  );

  /// See [HabitEntity.measureType].
  static final measureType = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[2],
  );

  /// See [HabitEntity.measureAmount].
  static final measureAmount = obx.QueryIntegerProperty<HabitEntity>(
    _entities[0].properties[3],
  );

  /// See [HabitEntity.measureDescription].
  static final measureDescription = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[4],
  );

  /// See [HabitEntity.measureTimeInMinutes].
  static final measureTimeInMinutes = obx.QueryIntegerProperty<HabitEntity>(
    _entities[0].properties[5],
  );

  /// See [HabitEntity.measureRepetitionsCount].
  static final measureRepetitionsCount = obx.QueryIntegerProperty<HabitEntity>(
    _entities[0].properties[6],
  );

  /// See [HabitEntity.icon].
  static final icon = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[7],
  );

  /// See [HabitEntity.iconColor].
  static final iconColor = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[8],
  );

  /// See [HabitEntity.iconBackground].
  static final iconBackground = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[9],
  );

  /// See [HabitEntity.reminderTimestamp].
  static final reminderTimestamp = obx.QueryIntegerProperty<HabitEntity>(
    _entities[0].properties[10],
  );

  /// See [HabitEntity.reminderVibrate].
  static final reminderVibrate = obx.QueryBooleanProperty<HabitEntity>(
    _entities[0].properties[11],
  );

  /// See [HabitEntity.reminderSound].
  static final reminderSound = obx.QueryBooleanProperty<HabitEntity>(
    _entities[0].properties[12],
  );
}
